name: insuranceAdjuster Login Test on chrome browser Build

on:
  push:
    branches:
      - web-login-test

jobs:

  insuranceAdjuster-run:
    name: insuranceAdjuster login Test 
    runs-on: ubuntu-22.04 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
         node-version: 22


      - name: Install Dependencies
        working-directory: web-automation
        run: npm install

      - name: Run insuranceAdjuster login Test
        uses: cypress-io/github-action@v6
        with:
          working-directory: web-automation
          command: npm run test:insuranceAdjuster-login-test
        
          
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: insuranceAdjuster-login-report
          path: web-automation/cypress/reports/html
