name: Login Multi-Browser Tests - For all roles

on:
  push:
    branches:
      - web-login-test

jobs:
  cross-browser:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge, firefox]  # Auto run on all 3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: web-automation
        run: npm install

      - name: Run Cypress on each browser
        uses: cypress-io/github-action@v6
        if: always()      
        with:
          working-directory: web-automation
          install: false
          browser: ${{ matrix.browser }}
          headed: true
          spec: "**/*.cy.js"

      - name: Upload Mochawesome Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: multi-browser-${{ matrix.browser }}-report
          path: web-automation/cypress/reports/html
