name: SignUp Parallel Tests

on:
  push:
    branches:
      - web-signup-tests

jobs:
  cypress-parallel:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]   # parallel 4 runners (you can change)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: Web-Automatio
        run: npm install

      - name: Run Cypress Across Matrix in Parallel
        uses: cypress-io/github-action@v6
        with:
          working-directory: Web-Automatio
          install: false
          browser: chrome
          spec: "**/*.cy.js"
          
      - name: Upload Mochawesome HTML reports
        uses: actions/upload-artifact@v4
        with:
          name: SingnUpParallelTestReports
          path: Web-Automatio/cypress/reports/html
